#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_payment_system.pages
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pay_online")]
	public partial class headsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHead_detail(Head_detail instance);
    partial void UpdateHead_detail(Head_detail instance);
    partial void DeleteHead_detail(Head_detail instance);
    #endregion
		
		public headsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Pay_onlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public headsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public headsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public headsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public headsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Head_detail> Head_details
		{
			get
			{
				return this.GetTable<Head_detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Head_detail")]
	public partial class Head_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Fee_id;
		
		private string _Course;
		
		private short _sem;
		
		private decimal _Tution_fee;
		
		private decimal _Library_fee;
		
		private decimal _Sport_culture_fee;
		
		private decimal _Other_fee;
		
		private decimal _Exam_fee;
		
		private decimal _Exam_form_fee;
		
		private decimal _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFee_idChanging(decimal value);
    partial void OnFee_idChanged();
    partial void OnCourseChanging(string value);
    partial void OnCourseChanged();
    partial void OnsemChanging(short value);
    partial void OnsemChanged();
    partial void OnTution_feeChanging(decimal value);
    partial void OnTution_feeChanged();
    partial void OnLibrary_feeChanging(decimal value);
    partial void OnLibrary_feeChanged();
    partial void OnSport_culture_feeChanging(decimal value);
    partial void OnSport_culture_feeChanged();
    partial void OnOther_feeChanging(decimal value);
    partial void OnOther_feeChanged();
    partial void OnExam_feeChanging(decimal value);
    partial void OnExam_feeChanged();
    partial void OnExam_form_feeChanging(decimal value);
    partial void OnExam_form_feeChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    #endregion
		
		public Head_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_id", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Fee_id
		{
			get
			{
				return this._Fee_id;
			}
			set
			{
				if ((this._Fee_id != value))
				{
					this.OnFee_idChanging(value);
					this.SendPropertyChanging();
					this._Fee_id = value;
					this.SendPropertyChanged("Fee_id");
					this.OnFee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this.OnCourseChanging(value);
					this.SendPropertyChanging();
					this._Course = value;
					this.SendPropertyChanged("Course");
					this.OnCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem", DbType="SmallInt NOT NULL")]
		public short sem
		{
			get
			{
				return this._sem;
			}
			set
			{
				if ((this._sem != value))
				{
					this.OnsemChanging(value);
					this.SendPropertyChanging();
					this._sem = value;
					this.SendPropertyChanged("sem");
					this.OnsemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tution_fee", DbType="Money NOT NULL")]
		public decimal Tution_fee
		{
			get
			{
				return this._Tution_fee;
			}
			set
			{
				if ((this._Tution_fee != value))
				{
					this.OnTution_feeChanging(value);
					this.SendPropertyChanging();
					this._Tution_fee = value;
					this.SendPropertyChanged("Tution_fee");
					this.OnTution_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Library_fee", DbType="Money NOT NULL")]
		public decimal Library_fee
		{
			get
			{
				return this._Library_fee;
			}
			set
			{
				if ((this._Library_fee != value))
				{
					this.OnLibrary_feeChanging(value);
					this.SendPropertyChanging();
					this._Library_fee = value;
					this.SendPropertyChanged("Library_fee");
					this.OnLibrary_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sport_culture_fee", DbType="Money NOT NULL")]
		public decimal Sport_culture_fee
		{
			get
			{
				return this._Sport_culture_fee;
			}
			set
			{
				if ((this._Sport_culture_fee != value))
				{
					this.OnSport_culture_feeChanging(value);
					this.SendPropertyChanging();
					this._Sport_culture_fee = value;
					this.SendPropertyChanged("Sport_culture_fee");
					this.OnSport_culture_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_fee", DbType="Money NOT NULL")]
		public decimal Other_fee
		{
			get
			{
				return this._Other_fee;
			}
			set
			{
				if ((this._Other_fee != value))
				{
					this.OnOther_feeChanging(value);
					this.SendPropertyChanging();
					this._Other_fee = value;
					this.SendPropertyChanged("Other_fee");
					this.OnOther_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exam_fee", DbType="Money NOT NULL")]
		public decimal Exam_fee
		{
			get
			{
				return this._Exam_fee;
			}
			set
			{
				if ((this._Exam_fee != value))
				{
					this.OnExam_feeChanging(value);
					this.SendPropertyChanging();
					this._Exam_fee = value;
					this.SendPropertyChanged("Exam_fee");
					this.OnExam_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exam_form_fee", DbType="Money NOT NULL")]
		public decimal Exam_form_fee
		{
			get
			{
				return this._Exam_form_fee;
			}
			set
			{
				if ((this._Exam_form_fee != value))
				{
					this.OnExam_form_feeChanging(value);
					this.SendPropertyChanging();
					this._Exam_form_fee = value;
					this.SendPropertyChanged("Exam_form_fee");
					this.OnExam_form_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
