<?xml version="1.0" encoding="utf-8"?><Database Name="Pay_online" Class="headsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;C:\Users\SHETTY SATYA\Documents\Pay_online.mdf&quot;;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Pay_onlineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Head_detail" Member="Head_details">
    <Type Name="Head_detail">
      <Column Name="Fee_id" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Course" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="sem" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Tution_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Library_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Sport_culture_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Other_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Exam_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Exam_form_fee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>